### PR TITLE
Remove success from responses

### LINKED ISSUE #6: Remove "success" flag in responses
Responses currently include a `success` flag which is being ignored by clients. If we're not using it (we're currently using HTTP status codes), it should be removed.

### PR DESCRIPTION
**Pull request by zaach**
fixes #6

### CODE REVIEW

**Comment by ckarlof** [comment]
Thanks Zach. Looks good to me. I'll let you and Ryan handle the merging of the server PRs.

**Comment by rfk** [comment]
This needs a rebase/merge due to refactoring of the route config in another commit.

**Comment by zaach** [comment]
@rfk thanks, rebased.

**Comment by rfk** [comment]
routes/user.js, line 24, a "success" might have snuck back in during the rebase?

**Comment by zaach** [comment]
@rfk fixed

**Comment by rfk** [comment]
r+

**Pull request merged**
